local handler = require("i3.handler")
local layout = require("i3.layout")

mainHandler = handler.new()

hs.hotkey.bind({"cmd", "alt", "ctrl"}, ",", function()
    mainHandler:setRoot()
end)

hs.hotkey.bind({"cmd", "alt"}, "j", function()
    mainHandler:selected():focusDown()
end)
hs.hotkey.bind({"cmd", "alt"}, "k", function()
    mainHandler:selected():focusUp()
end)
hs.hotkey.bind({"cmd", "alt"}, "h", function()
    mainHandler:selected():focusLeft()
end)
hs.hotkey.bind({"cmd", "alt"}, "l", function()
    mainHandler:selected():focusRight()
end)
hs.hotkey.bind({"cmd", "alt"}, ";", function()
    mainHandler:selected():focusPreviousStacked()
end)
hs.hotkey.bind({"cmd", "alt"}, "'", function()
    mainHandler:selected():focusNextStacked()
end)

hs.hotkey.bind({"cmd", "alt", "shift"}, "j", function()
    mainHandler:selected():swapDown()
end)
hs.hotkey.bind({"cmd", "alt", "shift"}, "k", function()
    mainHandler:selected():swapUp()
end)
hs.hotkey.bind({"cmd", "alt", "shift"}, "h", function()
    mainHandler:selected():swapLeft()
end)
hs.hotkey.bind({"cmd", "alt", "shift"}, "l", function()
    mainHandler:selected():swapRight()
end)

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "j", function()
    mainHandler:selected():shorter()
end)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "k", function()
    mainHandler:selected():taller()
end)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "h", function()
    mainHandler:selected():thinner()
end)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "l", function()
    mainHandler:selected():wider()
end)

hs.hotkey.bind({"cmd", "shift"}, "v", function()
    mainHandler:selected():verticalMode()
end)
hs.hotkey.bind({"cmd", "shift"}, "h", function()
    mainHandler:selected():horizontalMode()
end)

hs.hotkey.bind({"cmd", "alt"}, "m", function()
    mainHandler:selected():focusParent()
end)
hs.hotkey.bind({"cmd", "alt"}, "n", function()
    mainHandler:selected():focusChild()
end)
